{{- $flywayEnabled := and .Values.deployment .Values.deployment.flywayInitContainer .Values.deployment.flywayInitContainer.create -}}
{{- $migrationsConfigmap := "" -}}
{{- if and $flywayEnabled .Values.deployment.flywayInitContainer.migrationsConfigmap -}}
{{- $migrationsConfigmap = .Values.deployment.flywayInitContainer.migrationsConfigmap -}}
{{- end -}}
{{- $migrationsRoot := .Values.migrations | default dict -}}
{{- $allFlywayConfigmaps := .Values.migrations | default dict -}}
{{- $selectedMigrations := dict -}}
{{- if and $migrationsConfigmap (hasKey $migrationsRoot $migrationsConfigmap) -}}
{{- $selectedMigrations = index $migrationsRoot $migrationsConfigmap -}}
{{- end -}}
{{- if and $flywayEnabled $migrationsConfigmap (gt (len $selectedMigrations) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $migrationsConfigmap }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := $selectedMigrations }}
  {{ $key }}: |-
{{ $val | nindent 4 }}
  {{- end }}
{{- end }}
