{{- if and .Values.externalSecrets .Values.externalSecrets.initContainer .Values.externalSecrets.initContainer.create }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-flyway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
    {{- if .Values.externalSecrets.initContainer.labels }}
    {{- toYaml .Values.externalSecrets.initContainer.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.externalSecrets.initContainer.annotations }}
  annotations:
    {{- toYaml .Values.externalSecrets.initContainer.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshPolicy: {{ .Values.externalSecrets.initContainer.refreshPolicy }}
  refreshInterval: {{ .Values.externalSecrets.initContainer.refreshInterval | quote }}
  secretStoreRef:
    {{- if .Values.externalSecrets.initContainer.secretStoreRef }}
    name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.externalSecrets.initContainer.secretStoreRef.name "context" $) }}
    kind: {{ .Values.externalSecrets.initContainer.secretStoreRef.kind | default "SecretStore" }}
    {{- else }}
    {{- fail "secretStoreRef is required for ExternalSecret" }}
    {{- end }}
  target:
    name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" (.Values.externalSecrets.initContainer.targetSecret.name | default (printf "%s-flyway" .Values.name)) "context" $) }}
    creationPolicy: {{ .Values.externalSecrets.initContainer.targetSecret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.initContainer.targetSecret.deletionPolicy }}
    {{- if .Values.externalSecrets.initContainer.data }}
    template:
      type: Opaque
      metadata:
        annotations:
          externalsecret/secret-applied-hash: {{ include "externalsecrets.contractMarker" (dict "data" .Values.externalSecrets.initContainer.data) }}
    {{- end }}
  {{- if .Values.externalSecrets.initContainer.data }}
  data:
    {{- range .Values.externalSecrets.initContainer.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        {{- $key := include "interop-eks-microservice-chart.render-template" (dict "value" .remoteRef.key "context" $) }}
        key: {{ $key }}
        {{- if .remoteRef.property }}
        property: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .remoteRef.property "context" $) }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
        {{- if .remoteRef.conversionStrategy }}
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
