{{- if .Values.externalSecrets.create }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
    {{- if .Values.externalSecrets.labels }}
    {{- toYaml .Values.externalSecrets.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.externalSecrets.annotations }}
  annotations:
    {{- toYaml .Values.externalSecrets.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshPolicy: {{ .Values.externalSecrets.refreshPolicy }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    {{- if .Values.externalSecrets.secretStoreRef }}
    name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.externalSecrets.secretStoreRef.name "context" $) }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "SecretStore" }}
    {{- else }}
    {{- fail "secretStoreRef is required for ExternalSecret" }}
    {{- end }}
  target:
    name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" (.Values.externalSecrets.targetSecret.name | default .Values.name) "context" $) }}
    creationPolicy: {{ .Values.externalSecrets.targetSecret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.targetSecret.deletionPolicy }}
    {{- if or .Values.externalSecrets.data .Values.externalSecrets.dataFrom }}
    template:
      type: Opaque
      metadata:
        annotations:
          externalsecret/secret-applied-hash: {{ include "externalsecrets.contractMarker" . }}
    {{- end }}
  {{- if .Values.externalSecrets.data }}
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        {{- $key := include "interop-eks-microservice-chart.render-template" (dict "value" .remoteRef.key "context" $) }}
        key: {{ $key }}
        {{- if .remoteRef.property }}
        property: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .remoteRef.property "context" $) }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
        {{- if .remoteRef.conversionStrategy }}
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.externalSecrets.dataFrom }}
  dataFrom:
    {{- range .Values.externalSecrets.dataFrom }}
    - {{- if .sourceRef }}
      sourceRef:
        generatorRef:
          apiVersion: {{ .sourceRef.generatorRef.apiVersion }}
          kind: {{ .sourceRef.generatorRef.kind }}
          name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .sourceRef.generatorRef.name "context" $) }}
    {{- else if .extract }}
      extract:
        key: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .extract.key "context" $) }}
        {{- if .extract.version }}
        version: {{ .extract.version }}
        {{- end }}
        {{- if .extract.property }}
        property: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .extract.property "context" $) }}
        {{- end }}
        {{- if .extract.conversionStrategy }}
        conversionStrategy: {{ .extract.conversionStrategy }}
        {{- end }}
        {{- if .extract.decodingStrategy }}
        decodingStrategy: {{ .extract.decodingStrategy }}
        {{- end }}
        {{- if .extract.metadataPolicy }}
        metadataPolicy: {{ .extract.metadataPolicy }}
        {{- end }}
      {{- if .rewrite }}
      rewrite:
        {{- toYaml .rewrite | nindent 6 }}
      {{- end }}
    {{- else if .find }}
      find:
        {{- if .find.path }}
        path: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .find.path "context" $) }}
        {{- end }}
        {{- if .find.name }}
        name:
          regexp: {{ .find.name.regexp }}
        {{- end }}
        {{- if .find.tags }}
        tags:
          {{- toYaml .find.tags | nindent 10 }}
        {{- end }}
        {{- if .find.conversionStrategy }}
        conversionStrategy: {{ .find.conversionStrategy }}
        {{- end }}
        {{- if .find.decodingStrategy }}
        decodingStrategy: {{ .find.decodingStrategy }}
        {{- end }}
      {{- if .rewrite }}
      rewrite:
        {{- toYaml .rewrite | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
