{{- if and .Values.ingress .Values.ingress.create .Values.service.targetGroupArn }}
  {{ fail "ingress.create and service.targetGroupArn cannot both be configured; please define just one." }}
{{- end }}

{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx") }}
{{- $rulesByHost := include "interop-eks-microservice-chart.ingress-rules-by-host" .Values.ingress.rules | fromYaml | default (dict) }}

{{- $defaultAnnotations := dict
  "nginx.org/proxy-connect-timeout" "10s"
  "nginx.org/proxy-read-timeout" "28s"
  "nginx.org/proxy-send-timeout" "10s"
  "nginx.org/client-max-body-size" "10m" }}
{{- $mergedAnnotations := mergeOverwrite $defaultAnnotations ((.Values.ingress.annotations) | default dict) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $mergedAnnotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range $host, $paths := $rulesByHost }}
    - host: {{ include "interop-eks-microservice-chart.render-template" (dict "value" $host "context" $) | quote }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path.path | quote }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: {{ $.Values.service.containerPort }}
          {{- end }}
    {{- end }}
{{- end }}
