{{- if and .Values.argocd .Values.argocd.appMonitoring .Values.argocd.appMonitoring.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-tf-apply-monitoring
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded #To check what does this value do
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.argocd.appMonitoring.serviceAccountName "context" $) }}
      containers:
        - name: {{ .Values.name }}-tf-apply-monitoring
          image: alpine:3.20
          env:
            - name: ENV
              value: {{ .Values.local.env | quote }}
            - name: TF_VAR_argocd_workload_name
              value: {{ .Values.name | quote }}
            - name: TF_VAR_argocd_workload_kind
              value: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.argocd.appMonitoring.workloadKind "context" $) | quote }}
            - name: PROJECT_REPOSITORY_URL
              value: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.argocd.appMonitoring.projectRepositoryURL "context" $) | quote }}
            - name: PROJECT_REPO_REF
              value: {{ include "interop-eks-microservice-chart.render-template" (dict "value" .Values.argocd.appMonitoring.projectRepositoryRef "context" $) | quote }}
          command: ["/bin/sh", "-eu", "-c"]
          args:
            - |
              apk add --no-cache git curl unzip bash aws-cli >/dev/null

              git clone --depth 1 https://github.com/tfutils/tfenv.git /opt/tfenv
              export PATH="/opt/tfenv/bin:$PATH"

              git clone --branch "$PROJECT_REPO_REF" "$PROJECT_REPOSITORY_URL"
              cd "$(basename "$PROJECT_REPOSITORY_URL" .git)"/terraform

              TF_VERSION="$(cat ./.terraform-version)"
              tfenv install "$TF_VERSION"
              tfenv use "$TF_VERSION"

              cd k8s-monitoring-argocd-application

              REPO_NAME="$(basename "${PROJECT_REPOSITORY_URL%.git}")"

              terraform init \
              -backend-config="./env/${ENV}/backend.tfvars" \
              -backend-config="key=${ENV}-es1/${REPO_NAME}/argocd-applications/monitoring/${TF_VAR_argocd_workload_name}.tfstate"

              terraform apply -var-file="./env/${ENV}/terraform.tfvars" -auto-approve
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
{{- end }}