{{- if and .Values.autoscaling .Values.autoscaling.keda.create .Values.autoscaling.keda.scaledObjectSpec }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
spec:
  {{- with .Values.autoscaling.keda.scaledObjectSpec }}
  {{- include "interop-eks-microservice-chart.render-template" (dict "value" . "context" $) | nindent 2}}
  {{- end }}
{{- end }}