{{- if and .Values.autoscaling .Values.autoscaling.keda.create }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ .Values.name }}
  minReplicaCount: {{ .Values.autoscaling.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.keda.cooldownPeriod }}
  triggers:
    {{- $computedTriggers := include "interop-eks-microservice-chart.render-keda-triggers" (dict "triggers" .Values.autoscaling.keda.triggers "context" $.Values) | nindent 2 -}}
    {{- include "interop-eks-microservice-chart.render-template" (dict "value" $computedTriggers "context" $) }}
{{- end }}
