{{- if .Values.externalSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interop-eks-microservice-chart.render-template" (dict "value" (.Values.externalSecrets.targetSecret.name | default .Values.name) "context" $) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
  annotations:
    {{.Values.name}}/secret-data-hash: {{ include "externalsecrets.contractMarker" . }}
type: Opaque
stringData: {}
{{- end }}

