{{- if .Values.service.create }}

{{- if and (or .Values.service.healthcheck.port .Values.service.healthcheck.path .Values.service.healthcheck.successCodes ) .Values.service.targetGroupArn }}
  {{ fail "healthcheck and service.targetGroupArn cannot both be configured; please define just one." }}
{{- end }}

{{- $healthcheckPort := "" }}
{{- if  and .Values.service.healthcheck .Values.service.healthcheck.port }}
{{- $healthcheckPort = .Values.service.healthcheck.port }}
{{- else if .Values.service.servicePort -}}
{{- $healthcheckPort = .Values.service.servicePort }}
{{- else -}}
{{- $healthcheckPort = .Values.service.containerPort }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
  {{- if and .Values.service.albHealthCheck (or .Values.service.albHealthCheck.port .Values.service.albHealthCheck.path .Values.service.albHealthCheck.successCodes) }}
  annotations:
    {{- if .Values.service.albHealthCheck.protocol }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.service.albHealthCheck.protocol }}
    {{- end }}
    {{- if .Values.service.albHealthCheck.path }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.service.albHealthCheck.path | quote }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ $healthcheckPort | quote }}
    {{- if .Values.service.albHealthCheck.successCodes }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.service.albHealthCheck.successCodes | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if and .Values.service .Values.service.containerPort }}
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.servicePort | default .Values.service.containerPort }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.containerPort }}
      protocol: {{ .Values.service.containerProtocol | default "TCP" }}
    {{- end }}
    {{- if and .Values.service .Values.service.additionalPorts }}
    {{- range $key, $val := .Values.service.additionalPorts }}
    - name: {{ $val.name }}
      port: {{ $val.containerPort }}
      targetPort: {{ $val.targetPort | default $val.containerPort }}
      protocol: {{ $val.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "interop-eks-microservice-chart.selectorLabels" . | nindent 4 }}

{{- end }}
